### PR TITLE
Feature/kill

### PR DESCRIPTION
**Pull request by mawiswiss**
My container didn't reacted to `dde stop` or any other commands.

Any preferences here? @s4mpl3d @lukasluecke

### CODE REVIEW

**Comment by lukasluecke** [comment]
I'd rather not "pollute" `dde` with more "redundant" functionality of `docker-compose` - if this is something that's happening repeatedly we could add it for now, but I'd rather move towards removing the "dde lock-in", and allow / push consumers to use `docker-compose` directly for these tasks. This is an ongoing effort, and depends on at least #5 (since this is the main reason for the dependencies on `DDE_UID` etc., which cause normal `docker-compose` to fail).

**Comment by marcwieland95** [comment]
Good to hear and I fully agree. But yes, for the time being, it's very useful.

**Comment by lukasluecke** [comment]
I'd propose leaving this as an open PR in that case, so for anyone encountering the same issue there's a solution, and if there are more, we can still merge it.

As a temporary solution you can also use `DDE_UID=$(id -u) DDE_GID=$(id -g) docker-compose [command]` to "bypass" dde.

**Comment by marcwieland95** [comment]
I know, but that sucks. @s4mpl3d agreed that this PR would be useful

**Comment by lukasluecke** [comment]
Rebased to `develop` (Gitflow).

**Comment by Ruesa18** [comment]
@marcwieland95 Is this still an issue? I've never encountered something like this in this past year 🤔

**Comment by s4mpl3d** [comment]
Closing this PR since it references the old version of dde (Makefile)

**Pull request closed without merging**
